language: go
go:
- '1.9'
- tip
script: make ci
before_deploy: 
- pwd
- find .
- make archives
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
deploy:
  provider: releases
  api_key:
    secure: q3IcgkwFlX0rXYoVCR5Ll3hB0KwtMQp4SSFqK85HzfsHHylI0pkkZBAIUFu8EsDLgdHj6a3NMA/EbrOUBm3oQYNkBq7K9wAfvwfIz1jB4LTEhY42EiUDNnFW8d98vaJ5MzkV+6iB5+aJnqou9DVZwqLjjfpt0XeTKaiwyi3zOpEKxrc2Lqe7zjUiNeJld+hsrQn68YL3fsFNgJATksw0eSI2rMcKaiVzHLYgt/OBJ9WG7uc1cbcPLkAJZyFT78g8+2qvA1c1UUJUsxH/9C/WjpDg+Pim1L5zmhQuhHPUi45bSue+pWuunj2A8cupb6BrXU//QJbyHSy0+mySImYVaCyvRqASLkJrkNh+ugvC8l/xMP/3iRlnBmVrjJzOIQZFXRx/mxagRZxyYRtbvd1Z9+lr+YXYgg6ho74HgvQf60bSpuUPRWITtmb7WD9iOsNCbw2rh2Q9jLWkfo2w1194Q5aR8tGwUtCaNp+lVn4GfCdGw/8+cdcjC5k7zEsI3ssjTGMrDip6aNiPNnivFlISWpeFMLCB7+9BMoIFar6c5q0H37VASor4j9EFXpBvRNi++rQ/0XkVGF01hcwQkczQ/r2LuQ3IZ1QzKV4UO1TYkD2vx/CMavJ7voKSBdSNT+9SykIzJGdGc8iGBZGP30+QD4JUR7sIR/TwK9AGHPuUXLs=
  skip_cleanup: true
  file:
  - artifacts/archives/satis-go-darwin-amd64.tar.gz
  - artifacts/archives/satis-go-linux-amd64.tar.gz
  - artifacts/archives/satis-go-windows-amd64.zip
  - artifacts/archives/satis-go-darwin-386.tar.gz
  - artifacts/archives/satis-go-linux-386.tar.gz
  - artifacts/archives/satis-go-windows-386.zip
  go: '1.9'
  on:
    tags: true
